name: kube-linstor

version: v1.4.0
keywords:
  - linstor
  - drbd
home: https://github.com/kvaps/kube-linstor
sources:
  - https://hub.docker.com/r/kvaps/linstor-controller
  - https://hub.docker.com/r/kvaps/linstor-satellite
  - https://hub.docker.com/r/kvaps/linstor-stunnel
  - https://hub.docker.com/r/kvaps/linstor-operator
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
